ovros/urls.py
from django.contrib import admin
from django.urls import path, include
from ovros_home.views import (home,
                              services,
                              service_detail,
                              shops,
                              shop_detail,
                              )
from ovros_user_module import urls as account_urls
from ovros_dashboard import urls as dashboard_urls
from ovros_home.views import search
from ovros_service_module import urls as service_urls
from ovros_report_module import urls as report_urls
from ovros_booking import urls as booking_urls
from django.conf import settings
from django.conf.urls.static import static

admin.site.site_header = 'Ovros Admin'
admin.site.site_title = 'Ovros administration'
admin.site.index_title = 'Ovros Admin Dashboard'

urlpatterns = [
    # path('', home, name='home'),
    path('', home, name='home'),
    path('services/', services, name='services'),
    path('services/<int:service_id>', service_detail, name='service_detail_new'),
    path('shops/', shops, name='shops'),
    path('shops/<int:shop_id>', shop_detail, name='shop_detail'),
    path('search/', search, name='home_search'),
    path('admin/', admin.site.urls),
    path('account/', include(account_urls)),
    path('dashboard/', include(dashboard_urls)),
    path('service/', include(service_urls)),
    path('booking/', include(booking_urls)),
    path('report/', include(report_urls)),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ovros_user_module/models.py
from django.db import models
from django.conf import settings
from common.enums import DISTRICTS, DISTRICTS_CITY


class Types(models.TextChoices):
    USER_ADMIN = "USER_ADMIN", "UserAdmin"
    USER_SHOP = "USER_SHOP", "UserShop"
    USER_SHOP_MEMBER = "USER_SHOP_MEMBER", "UserShopMember"
    USER_CUSTOMER = "USER_CUSTOMER", "UserCustomer"


class ShopProfile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    user_role = models.CharField('Type', max_length=40, choices=Types.choices, default=Types.USER_SHOP)
    shop_name = models.CharField(max_length=100, help_text="Service Shop name")
    shop_profile_img = models.ImageField(upload_to='shops/profile_images', null=True, blank=True,
                                         default="shops/shop_profile_default.jpg",)
    shop_address_no = models.CharField(
        max_length=200,
        help_text="Service Shop address Number",
    )
    shop_address_street = models.CharField(
        max_length=200,
        help_text="Service Shop address street",
    )
    shop_address_city = models.CharField(
        choices=DISTRICTS_CITY,
        max_length=200,
        help_text="Service Shop address city",
    )
    shop_address_district = models.CharField(
        choices=DISTRICTS,
        max_length=200,
        help_text="Service Shop address district",
    )
    shop_contact = models.CharField(max_length=10, help_text="eg: 07xxxxxxxx")
    shop_email = models.CharField(max_length=100, help_text="shop email address", blank=True)

    def get_full_address(self):
        return f'No {self.shop_address_no} , ' \
               f'{self.shop_address_street}, ' \
               f'{self.shop_address_city}, ' \
               f'{self.shop_address_district}'

    def __str__(self):
        return f'Shop Profile for {self.shop_name}'


class UserProfile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    user_role = models.CharField('Type', max_length=40, choices=Types.choices, default=Types.USER_CUSTOMER)
    photo = models.ImageField(upload_to='users/%Y', blank=True,)
    contact_number = models.CharField(max_length=15, blank=True)
    created_at = models.DateTimeField(auto_created=True, null=True)

    def __str__(self):
        return f'Profile for user {self.user.username}'


class UserBankDetails(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    bank_name = models.CharField(max_length=100, help_text='Name of your Bank')
    bank_account_no = models.CharField(max_length=50)
    bank_branch = models.CharField(max_length=50)
    bank_account_name = models.CharField(max_length=100)

    def __str__(self):
        return f'Bank Account in {self.bank_name} account number is {self.bank_account_no}'

templates/shops/shop_detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    shop detail
{% endblock %}

{% block main_site_nav_shop_active %}
bg-warning
{% endblock %}

{% block main_body %}

    <!-- BREADCRUMB -->
    <nav class="bg-gray-200">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <!-- Breadcrumb -->
                    <ol class="breadcrumb breadcrumb-scroll">
                        <li class="breadcrumb-item">
                            <a href="{% url 'home' %}" class="text-gray-700"> ovros </a>
                        </li>
                        <li class="breadcrumb-item active" aria-current="page">shops</li>
                    </ol>
                </div>
            </div>
            <!-- / .row -->
        </div>
        <!-- / .container -->
    </nav>

    <!-- CONTENT -->
    <section>
        <!-- Content -->
        <div class="container d-flex flex-column">
            <div
                    class="row align-items-center justify-content-between gx-0 max-vh-100"
            >
                <div class="col-12 col-md-5 align-self-stretch">
                    <!-- Image (mobile) -->
                    <img
                            src="{{ profile.shop_profile_img.url }}"
                            class="d-md-none img-cover"
                            alt="..."
                    />

                    <!-- Image -->
                    <div
                            class="d-none d-md-block vw-50 h-100 float-end bg-cover"
                            style="background-image: url({% static 'main/img/covers/cover-5.jpg' %})"
                    ></div>
                </div>
                <div class="col-12 col-md-6 py-8 py-md-11">
                    <!-- Heading -->
                    <h2 class="fw-bold mb-2">{{ profile.shop_name }}</h2>

                    <!-- Text -->
                    <p class="fs-lg text-muted mb-0">
                        {{ profile.get_full_address }}
                    </p>
                    <p class="fs-lg text-muted mb-0">
                        {{ profile.shop_contact }}
                    </p>

                    <!-- Divider -->
                    <hr class="hr-sm my-6 my-md-8 mx-auto bg-gray-300"/>
                </div>
            </div>
            <!-- / .row -->
        </div>
    </section>

    <!-- ARTICLES -->

    {% if shop_services.count > 0 %}
        <section>
            <div class="row m-3"></div>
            <div class="container">
                <h2 class="fw-bold mb-2">Available Services</h2>
            </div>
            <div class="row m-3"></div>
        </section>
        <section>
            <div class="container">
                <div class="row">
                    {% for service in shop_services %}
                        <div class="col-12 col-md-6 col-lg-4 d-flex">

                            <!-- Card -->
                            <div class="card mb-6 shadow-light-lg lift lift-lg">

                                <!-- Image -->
                                <a class="card-img-top" href="{% url 'service_detail_new' service.id %}">

                                    <!-- Image -->
                                    <img src="{{ service.service_image.url }}" alt="..." class="card-img-top">

                                    <!-- Shape -->
                                    <div class="position-relative">
                                        <div class="shape shape-bottom shape-fluid-x text-white">
                                            <svg viewBox="0 0 2880 480" fill="none" xmlns="http://www.w3.org/2000/svg">
                                                <path fill-rule="evenodd" clip-rule="evenodd"
                                                      d="M2160 0C1440 240 720 240 720 240H0v240h2880V0h-720z"
                                                      fill="currentColor"/>
                                            </svg>
                                        </div>
                                    </div>

                                </a>

                                <!-- Body -->
                                <a class="card-body" href="{% url 'service_detail_new' service.id %}">

                                    <!-- Heading -->
                                    <h3>
                                        {{ service.service_name }}
                                    </h3>

                                    <!-- Text -->
                                    <p class="mb-0 text-muted">
                                        {{ service.service_description | truncatewords:15 }}
                                    </p>

                                </a>

                                <!-- Meta -->
                                <a class="card-meta mt-auto" href="#!">

                                    <!-- Divider -->
                                    <hr class="card-meta-divider">

                                    <!-- Avatar -->
                                    <div class="avatar avatar-sm me-2">
                                        <div style="display: inline-flex;">
                                            {% if service.is_for_car %}
                                                <img class="avatar-img rounded-circle" style="margin-right: 4px"
                                                     src="{% static 'icons/car_icon.png' %}">
                                            {% endif %}
                                            {% if service.is_for_van %}
                                                <img class="avatar-img rounded-circle" style="margin-right: 4px"
                                                     src="{% static 'icons/van_icon.png' %}">
                                            {% endif %}

                                            {% if service.is_for_suv %}
                                                <img class="avatar-img rounded-circle" style="margin-right: 4px"
                                                     src="{% static 'icons/suv_icon.png' %}">
                                            {% endif %}

                                            {% if service.is_for_lorry %}
                                                <img class="avatar-img rounded-circle" style="margin-right: 4px"
                                                     src="{% static 'icons/lorry_icon.png' %}">
                                            {% endif %}

                                            {% if service.is_for_bike %}
                                                <img class="avatar-img rounded-circle" style="margin-right: 4px"
                                                     src="{% static 'icons/bike_icon.png' %}">
                                            {% endif %}
                                            {% if service.is_for_long_vehicle %}
                                                <img class="avatar-img rounded-circle" style="margin-right: 4px"
                                                     src="{% static 'icons/long_vehicle_icon.png' %}">
                                            {% endif %}
                                        </div>
                                    </div>


                                </a>

                            </div>

                        </div>
                    {% endfor %}


                </div> <!-- / .row -->
            </div> <!-- / .container -->
        </section>
    {% endif %}




{% endblock %}

templates/shops/shop_detail___.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}
    Ovros Services
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row my-5 g-3">
            <div class="col-12 col-md-6 col-lg-4">
                <div class="card">
                    <div class="card-body text-center">
                        <img src="{{ profile.shop_profile_img.url }}" class="card-img-top"
                             alt="shop_profile_img">
                    </div>
                </div>
            </div>
            <div class="col-12 col-md-6 col-lg-8">
                <div class="card">
                    <div class="card-body text-center">
                        <h5 class="card-title"><strong>{{ profile.shop_name }}</strong></h5>
                        <div class="card-body ">
                            <div class="list-group">
                                <ul class="list-group list-group-flush">
                                    {% if profile.shop_email != "" %}
                                        <li class="list-group-item">
                                            <strong>Email :</strong><br>
                                            {{ profile.shop_email }}</li>
                                    {% endif %}

                                    <li class="list-group-item"><strong>Contact : </strong>{{ profile.shop_contact }}
                                    </li>
                                    <li class="list-group-item"><strong>Address : </strong>
                                        {{ profile.get_full_address }}</li>
                                </ul>
                            </div>

                        </div>
                    </div>

                </div>
            </div>
        </div>
        <div class="row my-5 g-3">
            <h3>Available Services ></h3>
        </div>

        <div class="row my-5 g-3">
            <div class="container">
            {% if shop_services.count == 0 %}
                No services yet
                {% else %}

                {% for service in shop_services %}
                    <div class="col-12 col-md-6 col-lg-4">
                        <div class="card">
                            <div class="card-body text-center">
                                {% if service.service_image is None %}
                                    <img src="{% static 'images/service_vector.jpg' %}" class="card-img-top"
                                         alt="...">
                                {% else %}
                                    <img src="{{ service.service_image.url }}" class="card-img-top" alt="...">
                                {% endif %}
                                <div class="card-body">
                                    <div class="list-group">
                                        <ul class="list-group list-group-flush">
                                            <li class="list-group-item">
                                                <h4>{{ service.service_name }}</h4>

                                            </li>
                                            <li class="list-group-item">
                                                <strong>Description :</strong><br>
                                                {{ service.service_description  | slice:":100" }} <a
                                                    href="{% url 'service_detail' service.id %}">read more...</a></li>
                                            <li class="list-group-item">
                                                <strong>Shop :</strong><br>
                                                {{ service.shop.shop_name }}</li>
                                            <li class="list-group-item"><strong>Price
                                                : </strong><span>Rs.</span>{{ service.service_price }}</li>
                                            <li class="list-group-item"><strong>Avg Duration </strong>
                                                : {{ service.service_duration }} minutes
                                            </li>
                                            <li class="list-group-item"><strong>Location </strong>
                                                : {{ service.shop.get_full_address }}
                                            </li>
                                            <li class="list-group-item"><strong>Available Vehicles </strong>
                                                <div>
                                                    {% if service.is_for_car %}
                                                        <img height="40px" width="40px"
                                                             src="{% static 'icons/car_icon.png' %}">
                                                    {% endif %}
                                                    {% if service.is_for_van %}
                                                        <img height="40px" width="40px" class="bi"
                                                             src="{% static 'icons/van_icon.png' %}">
                                                    {% endif %}

                                                    {% if service.is_for_suv %}
                                                        <img height="40px" width="40px" class="bi"
                                                             src="{% static 'icons/suv_icon.png' %}">
                                                    {% endif %}

                                                    {% if service.is_for_lorry %}
                                                        <img height="40px" width="40px" class="bi"
                                                             src="{% static 'icons/lorry_icon.png' %}">
                                                    {% endif %}

                                                    {% if service.is_for_bike %}
                                                        <img height="40px" width="40px" class="bi"
                                                             src="{% static 'icons/bike_icon.png' %}">
                                                    {% endif %}
                                                    {% if service.is_for_long_vehicle %}
                                                        <img height="40px" width="40px" class="bi"
                                                             src="{% static 'icons/long_vehicle_icon.png' %}">
                                                    {% endif %}

                                                </div>
                                            </li>
                                        </ul>
                                    </div>

                                </div>
                                <div class="card-footer">
                                    <a href="{% url 'service_detail' service.id %}" class="btn btn-primary ">View
                                        Details</a>

                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% endif %}

            </div>
        </div>
    </div>
{% endblock %}

templates/shops/shop_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Ovros-Shops
{% endblock %}

{% block main_site_nav_shop_active %}
bg-warning
{% endblock %}

{% block main_body %}

    <!-- BREADCRUMB -->
    <nav class="bg-gray-200">
        <div class="container">
            <div class="row">
                <div class="col-12">

                    <!-- Breadcrumb -->
                    <ol class="breadcrumb breadcrumb-scroll">
                        <li class="breadcrumb-item">
                            <a href="{% url 'home' %}" class="text-gray-700">
                                ovros
                            </a>
                        </li>
                        <li class="breadcrumb-item active" aria-current="page">
                            shops
                        </li>
                    </ol>

                </div>
            </div> <!-- / .row -->
        </div> <!-- / .container -->
    </nav>

    <!-- SEARCH -->
    <section class="py-6">
        <div class="container">
            <div class="row">
                <div class="col-12">

                    <!-- Form -->
                    <form class="rounded shadow" method="post">
                        {% csrf_token %}
                        <div class="input-group input-group-lg">

                            <!-- Text -->
                            <span class="input-group-text border-0 pe-1">
                  <i class="fe fe-search"></i>
                </span>

                            <!-- Input -->
                            <input type="text" name="{{ form.search_by_shop.html_name }}"
                                   class="form-control border-0 px-1" aria-label="Search for services"
                                   placeholder="Search for shops..." value="">

                            <!-- Text -->
                            <span class="input-group-text border-0 py-0 ps-1 pe-3">

                  <!-- Text -->
                  <span class="h6 text-uppercase text-muted d-none d-md-block mb-0 me-5">
                    {{ shops_profiles.count }} results
                  </span>

                                <!-- Button -->
                  <button type="submit" class="btn btn-sm btn-primary">
                    Search
                  </button>

                </span>

                        </div>
                    </form>

                </div>
            </div> <!-- / .row -->
        </div>
    </section>

    <section>
        {% if shops_profiles.count == 0 %}
            <div class="container">
                <div class="row mt-5">
                    <div class="col-lg-3 col-md-4"></div>
                    <div class="col-12 col-md-6 col-lg-6">
                        <h3>Oophss.. No Services Found !</h3>
                        <img alt="services not found" class="card-img-top"
                             src="{% static 'images/search_not_found.jpg' %}">
                    </div>
                    <div class="col-lg-3 col-md-4"></div>
                </div>

            </div>
        {% endif %}
    </section>

    <!-- ARTICLES -->
    <section>
        <div class="container">
            <div class="row">
                {% for profile in shops_profiles %}
                    <div class="col-12 col-md-6 col-lg-4 d-flex">

                        <!-- Card -->
                        <div class="card mb-6 shadow-light-lg lift lift-lg">

                            <!-- Image -->
                            <a class="card-img-top" href="{% url 'shop_detail' profile.id %}">

                                <!-- Image -->
                                <img src="{{ profile.shop_profile_img.url }}" alt="..." class="card-img-top">

                                <!-- Shape -->
                                <div class="position-relative">
                                    <div class="shape shape-bottom shape-fluid-x text-white">
                                        <svg viewBox="0 0 2880 480" fill="none" xmlns="http://www.w3.org/2000/svg">
                                            <path fill-rule="evenodd" clip-rule="evenodd"
                                                  d="M2160 0C1440 240 720 240 720 240H0v240h2880V0h-720z"
                                                  fill="currentColor"/>
                                        </svg>
                                    </div>
                                </div>

                            </a>
                            <!-- Body -->
                            <a class="card-body" href="{% url 'shop_detail' profile.id %}">

                                <!-- Heading -->
                                <h3>
                                    {{ profile.shop_name }}
                                </h3>
                                <!-- Text -->
                                <p class="mb-0 text-muted">
                                    {{ profile.get_shop_address_district_display }}
                                </p>
                                <p class="mb-0 text-muted">
                                    {{ profile.shop_contact }}
                                </p>
                                </p>
                                <p class="mb-0 text-muted">
                                    {{ profile.get_full_address }}
                                </p>

                            </a>
                            <!-- Meta -->
                            <a class="card-meta mt-auto" href="{% url 'shop_detail' profile.id %}">
                                <!-- Divider -->
                                <hr class="card-meta-divider">
                            </a>
                        </div>
                    </div>
                {% endfor %}

            </div> <!-- / .row -->
        </div> <!-- / .container -->
    </section>

    <!-- MORE -->
    <section class="py-7 py-md-10">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-12 col-md-9 col-lg-8 col-xl-7">

                    <!-- Button -->
                    <a href="#!" class="btn w-100 btn-outline-gray-300 d-flex align-items-center">
                        <span class="mx-auto">Load more</span> <i class="fe fe-arrow-right"></i>
                    </a>

                </div>
            </div> <!-- / .row -->
        </div> <!-- / .container -->
    </section>

    <!-- SHAPE -->
    <div class="position-relative">
        <div class="shape shape-bottom shape-fluid-x text-gray-200">
            <svg viewBox="0 0 2880 48" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path d="M0 48h2880V0h-720C1442.5 52 720 0 720 0H0v48z" fill="currentColor"/>
            </svg>
        </div>
    </div>



{% endblock %}

templates/shops/shop_list____.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}
    Ovros Services
{% endblock %}

{% block content %}

    <div class="container">
        <div class="row my-5 g-3">
            <div class="col-12 col-md-6 col-lg-4"></div>
            <div class="col-12 col-md-6 col-lg-4">
             <div class="accordion" id="accordionShopSearch">
                <div class="accordion-item">
                    <h2 class="accordion-header" id="headingOne">
                        <button class="accordion-button" type="button" data-bs-toggle="collapse"
                                data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                            Search  &nbsp;&nbsp; <i class="bi bi-search"></i>
                        </button>
                    </h2>
                    <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne"
                         data-bs-parent="#accordionShopSearch">
                        <div class="accordion-body">
                        <form method="post">
                            {% csrf_token %}
                            {{ form | crispy }}
                            <input class="btn btn-success" type="submit" value="Search">
                        </form>
                        </div>
                    </div>
                </div>

            </div>
            </div>
            <div class="col-12 col-md-6 col-lg-4"></div>

        </div>
        <div class="row my-5 g-3">
            {% for profile in shops_profiles %}
                <div class="col-12 col-md-6 col-lg-4">
                    <div class="card">
                        <img src="{{ profile.shop_profile_img.url }}" class="card-img-top">
                        <div class="card-body">
                            <div class="list-group">
                                <ul class="list-group list-group-flush">
                                    <li class="list-group-item">
                                        <h4><strong>{{ profile.shop_name }}</strong></h4>

                                    </li>
                                    {% if profile.shop_email != "" %}
                                        <li class="list-group-item">
                                            <strong>Email :</strong><br>
                                            {{ profile.shop_email }}</li>
                                    {% endif %}

                                    <li class="list-group-item"><strong>Contact : </strong>{{ profile.shop_contact }}
                                    </li>
                                    <li class="list-group-item"><strong>Address : </strong>
                                        {{ profile.get_full_address }}</li>
                                </ul>
                            </div>
                        </div>
                        <div class="card-footer text-center">
                            <a class="btn btn-primary" href="{% url 'shop_detail' profile.id %}">View Details</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>


{% endblock %}